### ISSUE TITLE
Multi-language support 

### ISSUE THREAD

**Issue by A-GG** [MarcoWorms/learn.js#15]
There are a lot of non-native English developers who is interested in JavaScript, and I think that providing multilingual support can help more people.

**Comment by MarcoWorms** [comment]
I'm translating this guide to portuguese (pt-br) since it's my main language, I don't know people who are good translators and javascript developers that are willing to translate for other languages but I'm open to talk about it!

**Comment by A-GG** [comment]
I'm a native Chinese speaker and I've been engaged in front-end for several years, maybe I can give it a try. But I don't know how you plan to organize the files.

**Comment by MarcoWorms** [comment]
@A-GG I'll push the file organization today after I translate some of the content, than you can just replicate it for chinese!

**Comment by MarcoWorms** [comment]
This will probably be done in about 12 hours, I'll mention you again in this thread when it's done ;)

**Comment by MarcoWorms** [comment]
Hey there @A-GG feel free to send a PR if you translate any part to chinese! I just added a structure to change language between files ;)

**Comment by MarcoWorms** [comment]
Since the repo now supports more languages and you already made the initial chinese version I'm closing this issue, feel free to open anything else your addition to this project was already amazing!! <3
