### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by dewball345** [MarcoWorms/learn.js#9]
Hey,

Just wanted to mention that you should add a CONTRIBUTING.md file to help people know if they should contribute, style info, suggestions, what to contribute on, etc. 

Github should offer some templates for default, so it shouldn't be that hard

**Comment by MarcoWorms** [comment]
I'll see about expanding this section https://github.com/MarcoWorms/learn.js#contribute and then move it to CONTRIBUTING.md, makes sense to me, thanks!!

**Comment by MarcoWorms** [comment]
Sorry if the project is still not contribution friendly, I hope to fix this after I release the next batch of content!

**Comment by MarcoWorms** [comment]
done!
